// import { ISoal } from "../pages/ujian";

// export const soalBIList: ISoal[] = [
//     {
//         ujian_id: 1,
//         nomor: 1,
//         tipe_soal: 'pilihan_ganda',
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Kata baku adalah kata yang sesuai dengan kaidah bahasa Indonesia yang benar.",
//         pertanyaan: "Manakah kata baku yang benar di antara pilihan berikut?",
//         pilihan_a: "aktifitas",
//         pilihan_b: "aktivitas",
//         pilihan_c: "efektifitas",
//         pilihan_d: "kwalitas",
//         pilihan_e: "",
//         jawaban: "b"
//     },
//     {
//         ujian_id: 1,
//         nomor: 2,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Antonim adalah kata yang memiliki makna berlawanan.",
//         pertanyaan: "Manakah antonim dari kata 'optimis'?",
//         pilihan_a: "pesimis",
//         pilihan_b: "realistis",
//         pilihan_c: "ambisius",
//         pilihan_d: "progresif",
//         pilihan_e: "",
//         jawaban: "a"
//     },
//     {
//         ujian_id: 1,
//         nomor: 3,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Sinonim adalah kata yang memiliki makna yang sama atau mirip.",
//         pertanyaan: "Manakah sinonim dari kata 'indah'?",
//         pilihan_a: "buruk",
//         pilihan_b: "elok",
//         pilihan_c: "jelek",
//         pilihan_d: "kasar",
//         pilihan_e: "",
//         jawaban: "b"
//     },
//     {
//         ujian_id: 1,
//         nomor: 4,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Kalimat efektif adalah kalimat yang sesuai dengan kaidah bahasa dan mudah dipahami.",
//         pertanyaan: "Manakah contoh kalimat efektif di bawah ini?",
//         pilihan_a: "Saya mau pergi ke pasar karena ingin membeli sayur-sayuran yang segar.",
//         pilihan_b: "Saya ingin pergi ke pasar untuk membeli sayur.",
//         pilihan_c: "Ke pasar saya mau pergi membeli sayuran segar yang banyak.",
//         pilihan_d: "Pasar ingin saya datangi sebab saya mau membeli banyak sayur segar sekali.",
//         pilihan_e: "",
//         jawaban: "b"
//     },
//     {
//         ujian_id: 1,
//         nomor: 5,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Teks eksposisi adalah teks yang bertujuan untuk menjelaskan atau menginformasikan sesuatu secara jelas.",
//         pertanyaan: "Ciri utama teks eksposisi adalah...",
//         pilihan_a: "mengandung unsur imajinasi",
//         pilihan_b: "bersifat informatif dan faktual",
//         pilihan_c: "menggunakan bahasa figuratif",
//         pilihan_d: "mengutamakan perasaan penulis",
//         pilihan_e: "",
//         jawaban: "b"
//     },
//     {
//         ujian_id: 1,
//         nomor: 6,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Majas adalah gaya bahasa yang digunakan untuk memperindah suatu kalimat.",
//         pertanyaan: "Manakah contoh majas metafora di bawah ini?",
//         pilihan_a: "Pipit menangis tersedu-sedu karena kehilangan bonekanya.",
//         pilihan_b: "Wajahnya berseri-seri bagai mentari pagi.",
//         pilihan_c: "Anak itu adalah bintang di kelasnya.",
//         pilihan_d: "Ayah bekerja keras untuk menghidupi keluarganya.",
//         pilihan_e: "",
//         jawaban: "c"
//     },
//     {
//         ujian_id: 1,
//         nomor: 7,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Slogan adalah kalimat singkat yang menarik dan mudah diingat untuk menyampaikan pesan.",
//         pertanyaan: "Manakah contoh slogan yang tepat?",
//         pilihan_a: "Belajar itu penting agar pintar dan sukses.",
//         pilihan_b: "Mari kita jaga kebersihan lingkungan kita.",
//         pilihan_c: "Hemat energi, selamatkan bumi!",
//         pilihan_d: "Kesehatan adalah hal yang sangat berharga.",
//         pilihan_e: "",
//         jawaban: "c"
//     },
//     {
//         ujian_id: 1,
//         nomor: 8,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Paragraf deduktif adalah paragraf yang gagasan utamanya terletak di awal paragraf.",
//         pertanyaan: "Manakah ciri utama paragraf deduktif?",
//         pilihan_a: "Gagasan utama terletak di akhir paragraf.",
//         pilihan_b: "Gagasan utama terletak di tengah paragraf.",
//         pilihan_c: "Gagasan utama terletak di awal paragraf.",
//         pilihan_d: "Tidak memiliki gagasan utama yang jelas.",
//         pilihan_e: "",
//         jawaban: "c"
//     },
//     {
//         ujian_id: 1,
//         nomor: 9,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Cerpen adalah cerita pendek yang mengisahkan suatu peristiwa dalam satu alur cerita.",
//         pertanyaan: "Unsur utama dalam cerpen meliputi...",
//         pilihan_a: "tema, tokoh, latar, alur, dan amanat",
//         pilihan_b: "judul, isi, dan kesimpulan",
//         pilihan_c: "gambar, tokoh, dan narasi",
//         pilihan_d: "fakta, opini, dan kesimpulan",
//         pilihan_e: "",
//         jawaban: "a"
//     },
//     {
//         ujian_id: 1,
//         nomor: 10,
//         perintah: "Pilihlah jawaban yang benar!",
//         teks: "Puisi adalah bentuk karya sastra yang memiliki irama dan makna mendalam.",
//         pertanyaan: "Bagian dalam puisi yang terdiri dari kumpulan baris disebut...",
//         pilihan_a: "bait",
//         pilihan_b: "larik",
//         pilihan_c: "rima",
//         pilihan_d: "tema",
//         pilihan_e: "",
//         jawaban: "a"
//     }
// ]